/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nmf1;

import java.io.IOException;
import java.nio.charset.Charset;
import java.nio.charset.StandardCharsets;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Scanner;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.util.GregorianCalendar;

/**
 *
 * @author tosyngy
 */
public class NMFImplementation extends javax.swing.JFrame {

    final static Charset ENCODING = StandardCharsets.UTF_8;
    int i = 0;
    Vector<String> quest = new Vector<String>();
    Vector<String> ans = new Vector<String>();
    Vector<String> stu_ans = new Vector<String>();
    String question;
    String answer;
    LSA1 algo;
    String allAns = "";
    Variables1 var = new Variables1();
    String name;

    /**
     * Creates new form NMFImplementation
     */
    public NMFImplementation() throws IOException {
        initComponents();
        loadData();
        algo = new LSA1("", "", "");
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 51, 0));
        jLabel1.setText("Using Using Non-negative matrix factorization");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(110, 50, 540, 40);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 0));
        jLabel2.setText("ELECTRONIC ACCESSMENT FREE TEXT DOCUMENTATION ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 10, 770, 40);

        jTextArea3.setBackground(new java.awt.Color(153, 153, 153));
        jTextArea3.setColumns(20);
        jTextArea3.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(30, 140, 490, 120);

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea2.setColumns(20);
        jTextArea2.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jScrollPane1.setViewportView(jTextArea2);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(570, 120, 280, 330);

        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(0, 51, 51));
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(40, 320, 480, 130);

        jLabel4.setText("Question: ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 110, 90, 30);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 10)), "Question Accumulator", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 8))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(560, 100, 300, 370);

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Answer", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 10))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 290, 520, 180);

        jButton1.setText(">");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(810, 540, 60, 30);

        jButton2.setText("<");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(610, 70, 10, 10);

        jButton3.setText("Quit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(10, 540, 80, 30);

        jButton4.setText("Start");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(370, 540, 100, 30);

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 10)), "Question", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 8))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 100, 520, 170);

        jButton5.setText("Save");
        jButton5.setEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(480, 540, 100, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 879, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-895)/2, (screenSize.height-624)/2, 895, 624);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jTextArea1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Answer is Required");
            return;
        }
        if (i < 0) {
            i++;
        }

        processQ();
        i++;

        if (i < quest.size()) {
            jTextArea3.setText(quest.elementAt(i));
            jTextArea1.setText(stu_ans.elementAt(i));
        }
        if (i >= quest.size()) {
            jButton1.setEnabled(false);
            jButton2.setEnabled(true);
            jButton5.setEnabled(true);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (jTextArea1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Answer is Required");
            return;
        }
        if (i >= quest.size()) {
            i--;
        }
        processQ();
        i--;

        if (i < 0) {
            jButton1.setEnabled(true);
            jButton2.setEnabled(false);
        }
        if (i >= 0) {
            jTextArea3.setText(quest.elementAt(i));
            jTextArea1.setText(stu_ans.elementAt(i));
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        name = JOptionPane.showInputDialog("Enter A name");
        if (name.isEmpty()) {
            name = GregorianCalendar.getInstance().getTimeInMillis() + "";
        }
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        i = 0;
        try {
            jTextArea3.setText(quest.elementAt(i));
        } catch (Exception e) {
            e.printStackTrace();
        }
        jButton4.setEnabled(false);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {

            String path = "data/Answer/" + i;
            String ans = "";
            for (String string : stu_ans) {
                ans += string.trim() + "\n";
            }
            ans = ans.trim();
            algo.writeFile(path + name + ".txt", ans);

            // TODO add your handling code here:
        } catch (IOException ex) {
            //  Logger.getLogger(NMFImplementation.class.getName()).log(Level.SEVERE, null, ex);
        }
        jButton5.setEnabled(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NMFImplementation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NMFImplementation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NMFImplementation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NMFImplementation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new NMFImplementation().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(NMFImplementation.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables1 declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        stu_ans.addElement("");
        Path path = Paths.get("data/Question/question.txt");
        Path path2 = Paths.get("data/Answer/lecturer.txt");
        String eachLine = "";
        String eachLine2 = "";
        int i = 0;
        try {
            Scanner scanner = new Scanner(path, ENCODING.name());
            Scanner scanner2 = new Scanner(path2, ENCODING.name());
            while (scanner.hasNextLine()) {
                eachLine = scanner.nextLine();
                eachLine2 = scanner2.nextLine();
                String question = eachLine;
                String answer = eachLine2;
                quest.addElement(question);
                ans.addElement(answer);
                stu_ans.addElement("");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    void processQ() {
        try {
            stu_ans.addElement(jTextArea1.getText());
            jTextArea2.append("Question: " + jTextArea3.getText());
            jTextArea2.append("\nOriginal: " + ans.elementAt(i));
            jTextArea2.append("\nAnswer: " + jTextArea1.getText());

            //default algorith is LSA
            allAns = jTextArea2.getText();
            jTextArea2.append("\n\n");

        } catch (Exception e) {
            e.printStackTrace();
        }

        try {

            String path = "data/Answer/" + (i + 1) + "/";
            String ans = jTextArea1.getText();
            ans = ans.trim();
            algo.writeFile(path + name + ".txt", ans);

            // TODO add your handling code here:
        } catch (IOException ex) {
            //  Logger.getLogger(NMFImplementation.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
//    class showtick_ implements Runnable {
//
//        @Override
//        public void run() {
//            try {
//                lsa = new LSA1("nmf", ans.elementAt(i), jTextArea1.getText());
//            } catch (Exception e) {
//            }
//        }
//    }
}
